### ISSUE TITLE
OTI fails to start

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/oti#43]
This is with Debian jessie and the openjdk-8 backport (host ot22), and a completely empty database. As usual it's hard to distinguish a warning from a genuine error, but the kernel extensions business looks pretty serious.

    WARNING! You are using an unsupported Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
    Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
    Starting Neo4j Server...WARNING: not changing user
    process [30474]... waiting for server to be ready..SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/home/opentree/neo4j-oti/system/lib/logback-classic-0.9.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/home/opentree/neo4j-oti/plugins/oti-neo4j-plugins-0.0.1-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    19:21:42,199 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
    19:21:42,199 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
    19:21:42,199 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/opentree/neo4j-oti/system/lib/neo4j-server-1.9.5.jar!/logback.xml]
    19:21:42,200 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
    19:21:42,200 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/opentree/neo4j-oti/system/lib/neo4j-server-1.9.5.jar!/logback.xml]
    19:21:42,200 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/opentree/neo4j-oti/plugins/oti-neo4j-plugins-0.0.1-SNAPSHOT.jar!/logback.xml]
    19:21:42,210 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@3834d63f - URL [jar:file:/home/opentree/neo4j-oti/system/lib/neo4j-server-1.9.5.jar!/logback.xml] is not of type file
    19:21:42,241 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
    19:21:42,244 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
    19:21:42,246 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
    19:21:42,264 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
    19:21:42,273 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
    19:21:42,273 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
    19:21:42,275 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1ae369b7 - Registering current configuration as safe fallback point

    2015-07-31 19:21:42.279+0000 DEBUG [API] You are using an unsupported Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
    2015-07-31 19:21:42.348+0000 INFO  [API] Setting startup timeout to: 120000ms based on -1
    Detected incorrectly shut down database, performing recovery..
    19:21:42.426 [main] WARN  o.neo4j.kernel.EmbeddedGraphDatabase - You are using an unsupported Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
    2015-07-31 19:21:42.836+0000 DEBUG [API] 
    org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@4cc8eb05' was successfully initialized, but failed to start. Please see attached cause exception.
            at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211) ~[neo4j-server-1.9.5.jar:1.9.5]
            at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87) [neo4j-server-1.9.5.jar:1.9.5]
            at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50) [neo4j-server-1.9.5.jar:1.9.5]
    Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@4cc8eb05' was successfully initialized, but failed to start. Please see attached cause exception.
            at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:284) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:106) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:88) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:207) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.impl.recovery.StoreRecoverer.recover(StoreRecoverer.java:114) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.server.preflight.PerformRecoveryIfNecessary.run(PerformRecoveryIfNecessary.java:59) ~[neo4j-server-1.9.5.jar:1.9.5]
            at org.neo4j.server.preflight.PreFlightTasks.run(PreFlightTasks.java:70) ~[neo4j-server-1.9.5.jar:1.9.5]
            at org.neo4j.server.AbstractNeoServer.runPreflightTasks(AbstractNeoServer.java:276) ~[neo4j-server-1.9.5.jar:1.9.5]
            at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:162) ~[neo4j-server-1.9.5.jar:1.9.5]
            ... 2 common frames omitted
    Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@4cc8eb05' was successfully initialized, but failed to start. Please see attached cause exception.
            at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:497) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:104) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:262) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            ... 10 common frames omitted
    Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.index.lucene.LuceneKernelExtension@6a370f4' was successfully initialized, but failed to start. Please see attached cause exception.
            at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:497) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:104) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:113) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:491) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            ... 12 common frames omitted
    Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.index.impl.lucene.LuceneDataSource@503d687a' was successfully initialized, but failed to start. Please see attached cause exception.
            at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:497) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.lifecycle.LifeSupport.bringToState(LifeSupport.java:404) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.lifecycle.LifeSupport.add(LifeSupport.java:318) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.impl.transaction.XaDataSourceManager.registerDataSource(XaDataSourceManager.java:196) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.index.lucene.LuceneKernelExtension.start(LuceneKernelExtension.java:86) ~[neo4j-lucene-index-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:491) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            ... 15 common frames omitted
    Caused by: org.neo4j.kernel.impl.storemigration.UpgradeNotAllowedByConfigurationException: Index version (managed by /home/opentree/neo4j-oti/data/graph.db/index/lucene-store.db) has changed and cannot be upgraded unless allow_store_upgrade=true is supplied in the configuration
            at org.neo4j.kernel.impl.index.IndexProviderStore.readRecordsWithNullDefaults(IndexProviderStore.java:133) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.impl.index.IndexProviderStore.<init>(IndexProviderStore.java:65) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.index.impl.lucene.LuceneDataSource.newIndexStore(LuceneDataSource.java:299) ~[neo4j-lucene-index-1.9.5.jar:1.9.5]
            at org.neo4j.index.impl.lucene.LuceneDataSource.start(LuceneDataSource.java:223) ~[neo4j-lucene-index-1.9.5.jar:1.9.5]
            at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:491) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            ... 20 common frames omitted
    2015-07-31 19:21:42.837+0000 DEBUG [API] Failed to start Neo Server on port [7478]
     Failed to start within 120 seconds.
    Neo4j Server may have failed to start, please check the logs.

**Comment by jar398** [comment]
For what it's worth, I'm getting something very similar with both taxomachine and treemachine: Component 'org.neo4j.index.lucene.LuceneKernelExtension@5ba3f27a' was successfully initialized, but failed to start.
and so on.

I don't understand what "Please see attached cause exception." means. I don't see any attached cause exception.

@chinchliff @blackrim @josephwb a little help here? I can give you access to the server.

**Comment by jar398** [comment]
Oh, I see it now, I bet it's the very last exception reported: Index version ... has changed and cannot be upgraded unless allow_store_upgrade=true is supplied in the configuration

which is odd given that there is no database to upgrade. I'll see if I can figure out which configuration file that goes in.

**Comment by jar398** [comment]
I tried uncommenting the line allow_store_upgrade=true in neo4j.properties and got this:

    Caused by: java.lang.NullPointerException: null
            at org.neo4j.kernel.impl.index.IndexProviderStore.<init>(IndexProviderStore.java:66) ~[neo4j-kernel-1.9.5.jar:1.9.5]
            at org.neo4j.index.impl.lucene.LuceneDataSource.newIndexStore(LuceneDataSource.java:299) ~[neo4j-lucene-index-1.9.5.jar:1.9.5]

For fun, I tried setting JAVA_HOME:

    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre

Perhaps that's the wrong value because this time when trying to start treemachine it just timed out - 'failed to start' with no null pointer exception.

**Comment by jar398** [comment]
Well this is the damnedest bug. I can provision a fresh server, and as long as I don't install one of the opentree applications, neo4j works just fine (any neo4j version, any java version). But if I install treemachine (or any other neo4j app) and the supporting packages that it needs, then neo4j stops working (it times out on initialization). And that means all neo4j instances - even for the admin user (treemachine et al are installed for the opentree user), and even ones that have no connection at all to opentree data or plugins.

That seems to imply that one of the debian package installations (apache, python, make, etc.) is clobbering something that neo4j depends on. This is hard to debug since the only way to narrow it down is to provision a new AWS instance and start over with installation. I will have to step through the setup sequence, firing up neo4j after each package installation, to find out what is interfering with neo4j. And even should I find the problem, I'm not sure what I would do at that point.

This does not give me a happy feeling about neo4j.

**Comment by jimallman** [comment]
Hmm. I noticed that some folks (in the related threads I found) fixed the problem by installing neo4j from a fresh tarball. Their implication was that it might be something dumb like file permissions.

**Comment by jar398** [comment]
I've done this many times already. The weird thing is that neo4j works
fine, then I install some stuff that does not touch any neo4j files, and
then neo4j fails. I've just done a test and narrowed it down to the first
four operations in as-admin.sh: setting the host name, and installing
dialog, rsync, and gcc. A few more tests and I should know exactly what
makes it fail.​

**Comment by jar398** [comment]
I got another nibble on the neo4j google group. The problem seems to have something to do with the 'hostname' command. Here is my latest post there:
https://groups.google.com/d/msg/neo4j/BNOdOChrEKI/ooLLRN5DBAAJ

**Comment by jimallman** [comment]
That matches some of the threads I've seen, where this error has turned out to be a network connection timeout.

**Comment by jar398** [comment]
https://groups.google.com/d/msg/neo4j/BNOdOChrEKI/b8OlBc2PBAAJ
