### ISSUE TITLE
Return "Preferred" status in `find_trees`

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/oti#55]
In making a call to `find_trees`, it would be very useful to return which tree(s) is "Preferred". In the nexson, this property is apparently called `ot:candidateTreeForSynthesis`.

If this property was present in the results of `find_trees`, then the newicks are just one call away. Otherwise, the nexson would have to be downloaded and parsed.

**Comment by jar398** [comment]
If someone wants to tackle this, it's a very simple fix:

1. add the property (ies) to
ot-base/src/main/java/org/opentree/properties/OTVocabularyPredicate.java

2. add it to
oti/src/main/java/org/opentree/oti/indexproperties/IndexedPrimitiveProperties.java

**Comment by josephwb** [comment]
Trying now.

**Comment by jar398** [comment]
Getting it into the system is a more difficult proposition. I'll need to
rebuilt the taxomachine graphdb, restart taxomachine and oti, and reload
all the studies into oti. Any other fixes we should be doing at the same
time?

**Comment by josephwb** [comment]
I don't have any other requests.

Both of your changes above are implemented and deployed on dev. Things compiled fine, but I cannot reindex. 
```
./push.sh -c ../../deployed-systems/development/devapi.config index-db
host=devapi.opentreeoflife.org, admin=admin, pem=/home/josephwb/.ssh/opentree/opentree.pem, controller=josephwb
Syncing
as-admin.sh                                                       100% 9080     8.9KB/s   00:00    
Java 8 OK
Indexing studies from API at https://devapi.opentreeoflife.org/
Using the oti instance at: http://127.0.0.1:7478/db/data/
Using the studies from: https://devapi.opentreeoflife.org//../
Traceback (most recent call last):
  File "repo/oti/index_current_repo.py", line 77, in <module>
    main()
  File "repo/oti/index_current_repo.py", line 48, in main
    r.raise_for_status()
  File "/wd/opentree/venv/local/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://devapi.opentreeoflife.org//../study_list
```
